spring:
  application:
    name: microservicio_skills
  datasource:
    url: jdbc:postgresql://localhost:5432/microservicio_skills  # Cambia por el nombre de tu BD
    username: postgres                                    # Cambia por tu usuario de Postgres (ej. postgres)
    password: 2004                               # Cambia por tu contraseña
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Útil para que cree las tablas automáticamente mientras desarrollas
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080 # Puerto donde correrá el microservicio

# Configuración de Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
